# Matches ydkulks/cursor-dark.nvim (style = "dark")
# vim:ft=kitty
foreground                      #D8DEE9
background                      #1A1A1A
selection_foreground            #D8DEE9
selection_background            #2E2E2E
# Cursor colors
cursor                          #FFFFFF
cursor_text_color               #1A1A1A
# Tab bar colors
active_tab_foreground           #D8DEE9
active_tab_background           #2E2E2E
inactive_tab_foreground         #505050
inactive_tab_background         #1F1F1F
# The basic 16 colors
# black
color0  #2A2A2A
color8  #505050
# red
color1  #BF616A
color9  #BF616A
# green
color2  #A3BE8C
color10 #A3BE8C
# yellow
color3  #EFB080
color11 #EBC88D
# blue
color4  #85C1FC
color12 #85C1FC
# magenta
color5  #AA9BF5
color13 #C582BF
# cyan
color6  #88C0D0
color14 #83D6C5
# white
color7  #D8DEE9
color15 #D8DEE9
