bind -n C-l select-pane -R
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U

bind -n C-S-h split-window -h  # Split horizontally with Ctrl+Shift+h
bind -n C-S-v split-window -v  # Split vertically with Ctrl+Shift+v
